version: '2.1'

services:
  product:
    build: microservices/product-service
    mem_limit: 350m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - mongodb  
  
  recommendation:
    build: microservices/recommendation-service
    mem_limit: 350m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - mongodb  

  review:
    build: microservices/review-service
    mem_limit: 350m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      mysql:
        condition: service_healthy  


  product-composite:
    build: microservices/product-composite-service
    mem_limit: 350m
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker    

  mongodb:
    image: mongo:3.6.9
    mem_limit: 350m
    #container_name: mongodb
    ports:
      - "27017:27017"
    command: mongod --smallfiles
    #volumes:
    #  - productdata:/data/db

  mysql:
    image: mysql:5.7
    mem_limit: 350m
    #container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=welcome1
      - MYSQL_DATABASE=review-db
      - MYSQL_USER=administrator
      - MYSQL_PASSWORD=welcome1
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-uadministrator", "-pwelcome1", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10 
    #volumes:
    # - reviewdata:/var/lib/mysql  
    

#volumes:
  #productdata:
  #reviewdata: 