server:
  port: 7001
  error:
    include-message: always

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: product-db
      auto-index-creation: true

logging:
  level:
    root: INFO
    "[com.rajesh.microservices]": DEBUG
    "[org.springframework.data.mongodb.core.MongoTemplate]": DEBUG

---
spring:
  profiles: docker
  data:
    mongodb:
      host: mongodb

server:
  port: 8080
